config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  resources :articles do
    resources :comments
  end
  resources :tags
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings
  has_attached_file :image, styles: { thumb: "180x180>" }
  validates_attachment_content_type :image,
                      :content_type => ["image/jpg", "image/jpeg", "image/png"]
  validates :title, :body, presence: true
  
  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end
  
  def tag_list=(tags_string)
    tags = tags_string.split(",").collect { |t| t.downcase.strip }.uniq
    new_or_found_tags = tags.collect { |t| Tag.find_or_create_by(name: t) }
    self.tags = new_or_found_tags
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  has_many :taggings
  validates :author_name, :body, presence: true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper
  
  def index
    @articles = Article.all 
  end
  
  def show
    @article = Article.find(params[:id])
    @comments = @article.comments
    @comment = Comment.new
    @comment.article_id = @article.id
  end
  
  def new
    @article = Article.new 
  end
  
  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to article_path(@article)
      flash[:notice] = "New article created"
    else
      render "new"
    end
  end
  
  def edit
    @article = Article.find(params[:id]) 
  end
  
  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:notice] = "Article updated"
      redirect_to article_path(@article)
    else
      render "edit"
    end
  end
  
  def destroy
    Article.find(params[:id]).destroy
    flash[:notice] = "Article deleted"
    redirect_to articles_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include CommentsHelper
  
  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]
    
    if @comment.save
      redirect_to article_path(@comment.article)
    else
      @article = @comment.article 
      @comments = @comment.article.comments
      render 'articles/show'
    end
  end
  
  def destroy
    @article = Article.find(params[:article_id])
    @article.comments.find(params[:id]).destroy
    
    flash[:notice] = "Comment deleted"
    redirect_to @article
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end
  
  def show
    @tag = Tag.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  
  private
    def article_params
      params.require(:article).permit(:title, :body, :tag_list, :image)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
  private
    def comment_params
      params.require(:comment).permit(:author_name, :body)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_article.html.erb
<div class="article">
  
  <% if @articles %>
    <div class="article-title">
      <%= link_to article.title, article_path(article) %>
    </div>
  <% end %>
  
  <% if article.tags.any? %>
    <div class="tags">
      Tags: 
      <% article.tags.each do |tag| %>
        <%= link_to tag.name, tag_path(tag) %>
      <% end %>
    </div>
  <% end %>
  
  <% if article.image.exists? %>
    <div class="image">
      <% if @articles %>
        <%= image_tag article.image.url(:thumb) %>
      <% else %>
        <%= image_tag article.image.url, width: '100%' %>
      <% end %>
    </div>
  <% end %>
  
  <div class="article-body">
    <%= article.body %>
  </div>
  
  <div class="article-actions">
    <%= link_to "Edit", edit_article_path(article) %> | 
    <%= link_to "Delete", article_path(article),
                         method: :delete,
                         data: { confirm: "Are you sure?" } %>
  </div>
  <hr>
</div>

app/views/articles/_error_messages.html.erb
<div class="errors">
  <h3><%= pluralize(@article.errors.count, "error") %></h3>
  <ul>
    <% @article.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div> 

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>

  <% if @article.errors.any? %>
    <%= render 'error_messages' %>
  <% end %>
  
  <div class="title-field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div> 
  
  <div class="body-field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  
  <div class="tags-field">
    <%= f.label :tag_list %>
    <%= f.text_field :tag_list %>
  </div>
  
  <div class="image-field">
    <% if @article.image.exists? %>
      <%= image_tag @article.image.url(:thumb) %>
    <% end %>
    <%= f.label :image, "Attach a New image" %>
    <%= f.file_field :image %>
  </div>
  
  <div class="submit">
    <%= f.submit %>
  </div>
  
<% end %>
   

app/views/articles/edit.html.erb
<%= render "form" %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<div class="articles">
  <%= render @articles %>
</div>

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<div class="article">
  <%= render @article %>
</div>

<h3>Comments (<%= @comments.count %>)</h3>
<div class="comment">
  <%= render @comments %>
</div>

<div class="comment-form">
  <%= render "comments/form" %>
</div>

app/views/comments/_comment.html.erb
<div class="comment">
  <div class="comment-author">
    <%= comment.author_name %>
  </div>
  <div class="comment-body">
    <%= comment.body %>
  </div>
  <div class="time-posted">
    Posted <%= distance_of_time_in_words(comment.article.created_at,
                                         comment.created_at) %> ago
  </div>
  <div class="comment-actions">
    <%= link_to "Delete", article_comment_path(@article, comment),
                         method: :delete,
                         data: { confirm: "Are you sure?" } %>
  </div>
</div>

app/views/comments/_error_messages.html.erb
<div class="errors">
  <h3><%= pluralize(@comment.errors.count, "error") %></h3>
  <ul>
    <% @comment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div> 

app/views/comments/_form.html.erb
<%= form_for [ @article, @comment ] do |f| %>

  <% if @comment.errors.any? %>
    <%= render 'error_messages' %>
  <% end %>
  
  <div class="author-field">
    <%= f.label :author_name, "Your Name" %>
    <%= f.text_field :author_name %>
  </div> 
  <div class="body-field">
    <%= f.label :body, "Comment" %>
    <%= f.text_area :body %>
  </div>
  <div class="submit">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/_nav_links.html.erb
<hr>
<%= link_to "Create New Article", new_article_path %> | 
<%= link_to "All Articles", articles_path %> | 
<%= link_to "All Tags", tags_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <p class="flash"><%= flash[:notice] %></p>

  <%= yield %>

  <%= render 'layouts/nav_links' %>
  
</body>
</html>

app/views/tags/index.html.erb
<h1>All Tags (<%= @tags.count %>)</h1>

<ul>
  <% @tags.each do |tag| %>
    <li><%= link_to tag.name, tag_path(tag) %></li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<h1>Articles tagged with "<%= @tag.name %>" (<%= @tag.articles.count %>)</h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>